### PR TITLE
Analytics label based on @chemidy

### PR DESCRIPTION
**Pull request by willawang8908**
#301

### CODE REVIEW

**Comment by willawang8908** [comment]
I signed it!

**Comment by willawang8908** [comment]
@googlebot I consent.

**Comment by chemidy** [comment]
Of course i'm ok with that you can merge it.

**Comment by hiranya911** [comment]
@chemidy You need to put a comment with the text `@googlebot I consent`

**Comment by chemidy** [comment]
@googlebot I consent

**Comment by hiranya911** [comment]
Closes #303

**Comment by stripathi669** [comment]
@hiranya911 Can I check - when might you be planning to release this?

**Comment by hiranya911** [comment]
Most likely next week.

**Pull request merged**
