### PR TITLE
'?' is now an illegal character for the REST API

### PR DESCRIPTION
**Pull request by Bien-CV**
Having a '?' character in a path raised an ApiCallError (405 Client Error: Method Not Allowed for url: -fakeURLwith?-.json Reason: append .json to your request URI to use the REST API. ).

It is indeed not the right error. 

This pull request allows the correct error to be raised ( ValueError : 'Invalid path: "{0}". Path contains illegal characters.' ).

### CODE REVIEW

**Comment by Bien-CV** [comment]
CLA signed.

**Comment by hiranya911** [comment]
@Bien-CV thanks for the PR. However, `?` is a valid path character in Firebase Realtime Database. I wonder if we should do something special to handle them in Python.

@rockwotj any thoughts on how to fix this? Simple URL encoding of the "?" is not enough it seems.

**Comment by rockwotj** [comment]
@hiranya911 we've got a really bad bug that's been out for 5 years or something. We have broken behavior with URL decoding where we accidentally do it twice. That breaks most of these things, and we don't have a good fix because there are apps that rely on the broken behavior. We're trying to come up with a way to fix it.

**Comment by Bien-CV** [comment]
The '?' issue bothers all developers trying to use URLs as keys in firebase.

**Comment by hiranya911** [comment]
@rockwotj just wanted to ping you again on this. Is it reasonable to not accept `?` as a valid path character (at least until the issue in the server-side gets resolved)?

**Comment by rockwotj** [comment]
There is no harm, I'm fine with it. I'll ping this thread when the issue is deployed.

**Pull request merged**
