### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by Matt-Gleich**
General cleanup for opensource files and .travis.yml

### CODE REVIEW

**Comment by Matt-Gleich** [comment]
I signed the CLA, what did I do wrong?

**Comment by hiranya911** [comment]
> Once you've signed (or fixed any issues), please reply here with @googlebot I signed it!) and we'll verify it.

**Comment by Matt-Gleich** [comment]
@googlebot I signed it!

**Comment by Matt-Gleich** [comment]
@hiranya911 am I good on my end of things? I says that I signed the CLA.

**Pull request closed without merging**
