### PR TITLE
Add snippets to the admin repo

### PR DESCRIPTION
**Pull request by samtstern**
They are linted by `lint.sh`, not sure if that fails below a certain score?

### CODE REVIEW

**Comment by hiranya911** [comment]
The linter fails the build if it detects at least one error. But looks like the linter passed on this one. From the last build log:

```
$ if [[ "$PY_VERSION" == '2' ]]; then ./lint.sh all; fi
Running linter on module firebase_admin
Running linter on module tests
Running linter on module integration
Running linter on module snippets
```

We have more snippets at https://github.com/firebase/quickstart-python. I think we should move them here as well.

**Comment by samtstern** [comment]
@hiranya911 I added all the relevant `quickstart-python` snippets here and also moved the files around to be in subfolders.  Lint gets 10/10 now.

**Comment by samtstern** [comment]
However the `581a9dc` should have failed due to lint, and it did not...

**Comment by samtstern** [comment]
I'll wait for @hiranya911 to merge.

**Pull request merged**
