### PR TITLE
#61 add support to shallow param

### PR DESCRIPTION
**Pull request by rodolphopivetta**
I just added the param to [shallow](https://firebase.google.com/docs/database/rest/retrieve-data#shallow) results

### CODE REVIEW

**Comment by rodolphopivetta** [comment]
Google CLA account created

**Comment by rodolphopivetta** [comment]
Failed test solved in commit https://github.com/rodolphopivetta/firebase-admin-python/commit/3bc92f4cd34ba98755d258e0a039f38409a99317

**Comment by hiranya911** [comment]
Please fix the linter error detected by CI: https://travis-ci.org/firebase/firebase-admin-python/builds/289052233

You can run `./lint.sh all` locally to see what the output is like.

**Comment by rodolphopivetta** [comment]
I'll asap @hiranya911. Thanks

**Comment by hiranya911** [comment]
Closing in favor of #109. Thanks @rodolphopivetta for the contribution.

**Pull request closed without merging**
