### PR TITLE
Add subtitle to ApsAlert

### PR DESCRIPTION
**Pull request by dsanghan**
Tested for APNS. Works.

### CODE REVIEW

**Comment by hiranya911** [comment]
@dsanghan why was this closed?

**Comment by dsanghan** [comment]
I closed the issue and opened the PR

**Comment by hiranya911** [comment]
@dsanghan Can you fix the linter error detected by Travis (line-too-long)? Also please update the tests.

**Comment by hiranya911** [comment]
Closing in favor of #239

**Pull request closed without merging**
